name: 🛠️ Builds GDExtension
on:
  release:
    types: [created]
  
  schedule:
    - cron: "0 5 1,3,5,7,9,11,13,15,17,19,21,23,25,27,29 * *"
  
  workflow_dispatch:
    inputs:
      run:
        description: 'accept to build'
        required: false

permissions:
    contents: write

jobs:
  build:
    runs-on: windows-2022
    name: ${{ matrix.name }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - identifier: linux-debug-x86_64
            name: Linux Debug x86_64
            target: template_debug
            platform: linux
            arch: x86_64
          - identifier: linux-release-x86_64
            name: Linux Release x86_64
            target: template_release
            platform: linux
            arch: x86_64
          - identifier: windows-debug-x86_64
            name: Windows Debug x86_64
            target: template_debug
            platform: windows
            arch: x86_64
          - identifier: windows-release-x86_64
            name: Windows Release x86_64
            target: template_release
            platform: windows
            arch: x86_64
    steps:
      - name: Checkout project
        uses: actions/checkout@v4
        with:
          submodules: recursive
          fetch-depth: 0
      - name: Setup cmake
        uses: jwlawson/actions-setup-cmake@v2
        with:
          cmake-version: '4.0.x'
      
      - name: Setup MSVC    
        uses: TheMrMilchmann/setup-msvc-dev@v3
        with:
            arch: x64
      - name: Setup MSVC for x86
        uses: TheMrMilchmann/setup-msvc-dev@v3
        with:
            arch: x86
      
      - name: install dependencies
        shell: powershell
        run: |
          Set-ExecutionPolicy -ExecutionPolicy RemoteSigned -Scope CurrentUser
          Invoke-RestMethod -Uri https://get.scoop.sh | Invoke-Expression
          scoop bucket add main
          scoop install main/mingw
          scoop install main/python
      - name: Install Python and SCons
        uses: actions/setup-python@v2

      - name: Install SCons
        run: |
          python -m pip install --upgrade pip
          python -m pip install scons
      - name: Set up SCons cache
        uses: actions/cache@v3
        with:
          path: |
            ${{ github.workspace }}/.scons-cache/
            ${{ github.workspace }}/**/.sconsign.dblite
            ${{ github.workspace }}/godot-cpp/gen/
          key: ${{ matrix.identifier }}-${{ github.ref }}-${{ github.sha }}
          restore-keys: |
            ${{ matrix.identifier }}-${{ github.ref }}-
            ${{ matrix.identifier }}-
      - name: Compile extension
        shell: bash
        env:
          SCONS_CACHE: '${{ github.workspace }}/.scons-cache/'
          SCONS_CACHE_LIMIT: 4096
        run: |
          scons target='${{ matrix.target }}' platform='${{ matrix.platform }}' arch='${{ matrix.arch }}' -j2
          ls -l project/addons/*/bin/

      - name: Prepare artifacts with project files
        shell: bash
        run: |
          PROJECT_DIR="${{ github.workspace }}/project"
          ARTIFACT_DIR="${{ github.workspace }}/artifacts"
          
          # Copy root documentation to project directory
          cp -v "${{ github.workspace }}/README.md" "$PROJECT_DIR/"
          cp -v "${{ github.workspace }}/LICENSE" "$PROJECT_DIR/"

          # Create platform-specific zip
          mkdir -p "$ARTIFACT_DIR"
          ZIP_NAME="GD_Voxel_Terrain_Extension_${{ matrix.identifier }}.zip"
          cd "$PROJECT_DIR"
          7zip -r "$ARTIFACT_DIR/$ZIP_NAME" .

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: "GD_Voxel_Terrain_Extension_${{ matrix.identifier }}"
          path: ${{ github.workspace }}/artifacts/"GD_Voxel_Terrain_Extension_${{ matrix.identifier }}".zip

  release:
    runs-on: ubuntu-22.04
    needs: build
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          path: artifacts

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: "GDExtension-${{ github.ref_name }}"  # Use existing tag from release creation
          files: |
            artifacts/*.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
